### ISSUE TITLE
Artifacts Uploader fails with com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials$PrivateKeyNotSetException

### ISSUE THREAD

**Issue by gowrishankarsundersc** [jenkinsci/google-storage-plugin#19]
I am using the plugin to upload the build logs as well as a folder container xml artifacts to the same GCS bucket using the same credentials within the same build. The build logs upload fine but the artifact uploads fail with the following error:
`[Google Cloud Storage Uploader] Found 1 files to upload from pattern: artifacts/*.log
ERROR: Build step failed with exception
com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials$PrivateKeyNotSetException
    at com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.getGoogleCredential(GoogleRobotPrivateKeyCredentials.java:184)
    at com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.getGoogleCredential(GoogleRobotPrivateKeyCredentials.java:45)
    at com.google.jenkins.plugins.credentials.oauth.RemotableGoogleCredentials.<init>(RemotableGoogleCredentials.java:57)
    at com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentials.forRemote(GoogleRobotCredentials.java:204)
    at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:413)
    at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:101)
    at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:367)
    at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:364)
    at hudson.remoting.UserRequest.perform(UserRequest.java:120)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at hudson.remoting.Engine$1$1.run(Engine.java:85)
    at java.lang.Thread.run(Thread.java:745)
    at ......remote call to mac-slave-01(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
    at hudson.remoting.Channel.call(Channel.java:781)
    at hudson.FilePath.act(FilePath.java:1074)
    at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:363)
    at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:182)
    at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Google Cloud Storage Uploader' marked build as failure`

**Comment by gowrishankarsundersc** [comment]
This seems to happen after moving to Jenkins v2.0+ - not sure if that is related though

**Comment by andrewzhaosc** [comment]
amazing

**Comment by anniekvandijk** [comment]
Could this be the same problem? https://github.com/jenkinsci/google-oauth-plugin/issues/13
