### ISSUE TITLE
Null pointer exception for Gcloudstepdownload

### ISSUE THREAD

**Issue by selvakumar7991** [jenkinsci/google-storage-plugin#228]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

java.lang.NullPointerException
13:24:37  	at com.google.jenkins.plugins.storage.UploadModule.getStorageService(UploadModule.java:88)
13:24:37  	at com.google.jenkins.plugins.storage.DownloadStep.resolveBucketPath(DownloadStep.java:391)
13:24:37  	at com.google.jenkins.plugins.storage.DownloadStep.perform(DownloadStep.java:209)
13:24:37  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
13:24:37  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
13:24:37  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
13:24:37  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:24:37  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:24:37  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:24:37  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:24:37  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:24:37  	at java.lang.Thread.run(Thread.java:748)

### Expected Results

no issue, download the object from the bucket

### Actual Results

no issue, download the object from the bucket

### Anything else?

stage('GCS access') {
            steps {
                script {
 step([$class: 'DownloadStep', credentialsId: 'qa-automation-jobs-dev',  bucketUri: 'gs://searchservice/payloads/*.csv',
                      localDirectory: 'home'])

                } // end of script
            } // end of steps
}

**Comment by selvakumar7991** [comment]
Jenkins version : 2.289.1
[Google Cloud Storage](https://plugins.jenkins.io/google-storage-plugin) : 1.5.4.1

**Comment by selvakumar7991** [comment]
CC:@
Craig Barber
craigdbarber

**Comment by jlightwing-flooid** [comment]
Just had this issue, and in my case it was the credential id that was wrong. I corrected that and it worked. Obviously the null pointer isn't great.
