### ISSUE TITLE
java.lang.IllegalStateException on upgrade from 1.2 to 1.3.1

### ISSUE THREAD

**Issue by ken-ie** [jenkinsci/google-storage-plugin#82]
We are running Jenkins in a Kubernetes cluster. When we updated from Google Cloud Storage plugin from 1.2 to 1.3.1, all jobs with a google cloud upload failed. Downgrading to 1.2 resolved the issue.

**Google Cloud Storage Plugin**: 1.3.1
**Kubernetes Plugin**: 1.16.7

```
[Google Cloud Storage Plugin] Found 1 files to upload from pattern: jenkins-test-gcloud.txt
ERROR: Build step failed with exception
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.56.0.48/10.56.0.48:51760
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1162)
		at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:390)
		at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:176)
		at com.google.jenkins.plugins.storage.ClassicUploadStep.perform(ClassicUploadStep.java:183)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.Build$BuildExecution.build(Build.java:206)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
		at hudson.model.Run.execute(Run.java:1818)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
	at jenkins.model.Jenkins.get(Jenkins.java:769)
	at hudson.model.Hudson.getInstance(Hudson.java:77)
	at com.google.jenkins.plugins.storage.AbstractUpload.getDescriptor(AbstractUpload.java:365)
	at com.google.jenkins.plugins.storage.AbstractUpload.getModule(AbstractUpload.java:276)
	at com.google.jenkins.plugins.storage.AbstractUpload$2.<init>(AbstractUpload.java:445)
	at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:442)
	at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:94)
	at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:394)
	at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:391)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
Build step 'Google Storage Classic Upload' marked build as failure
```

(If this is, in fact, a problem with the Kubernetes executor pod, please let me know and I'll move this to the appropriate product!)

**Comment by Conky5** [comment]
We are seeing this as well.

**jenkins version:** 2.184
**Google Cloud Storage Plugin:** 1.3.1

**Comment by stephenashank** [comment]
@ken-ie What version of Jenkins are you using?
@Conky5 Are you using the Kubernetes plugin as well?

**Comment by ken-ie** [comment]
We are using Jenkins 2.184. Issue also appeared in Jenkin 2.183.

**Comment by Conky5** [comment]
@stephenashank we are not using the kubernetes plugin. Also confirmed downgrading to `1.2` of the google cloud storage plugin works.

**Comment by stephenashank** [comment]
Thanks for your responses. I was able to reproduce the IllegalStateException and fix it with #83. If you have the inclination, you can test the fix yourself before release by following the instructions I gave in this comment: https://github.com/jenkinsci/google-storage-plugin/issues/78#issuecomment-507890766, using 83 instead of 79 for the pull request number. Let me know if you experience any other issues.

**Comment by ken-ie** [comment]
@stephenashank 
I built and installed the image following the instructions you gave. (Version shows as 1.3.2-SNAPSHOT.(etc))
I can confirm that the fix works for uploads. Downloads were also tested and worked fine.

_Thank you for the quick response!_

**Comment by craigdbarber** [comment]
1.3.2 has been released incorporating this fix. Closing this.
